### ISSUE TITLE
db_url/db_url_with_pooler output variables are censored

### ISSUE THREAD

**Issue by ccavolt** [neondatabase/create-branch-action#12]
## Steps to reproduce
Use the latest version of the beta action

## Expected result
Be able to use db_url/db_url_with_pooler variables in subsequent jobs

## Actual result
GitHub Actions prevents sensitive information from becoming an output

## Environment
GitHub Actions

## Logs, links
- From GitHub Actions log: `Warning: Skip output 'db_url' since it may contain secret.`
                           `Warning: Skip output 'db_url_with_pooler' since it may contain secret.`

I'm not sure this is actually fixable (although I'm for sure not an expert) since GitHub is automatically censoring the outputs. Previously, I used string interpolation to create the database url like so: `DATABASE_URL: postgres://${{ vars.NEON_DB_USER }}:${{ secrets.NEON_DB_PASSWORD }}@${{ needs.create-neon-branch.outputs.host }}/${{ vars.NEON_DB_NAME }}` but due to #11 this workaround is no longer possible because I can't retrieve the host variable.

**Comment by duskpoet** [comment]
I would assume that github would hide passwords from logs. Were you able to solve this, since host is now present in the output?
