### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by jbwc** [neondatabase/create-branch-action#13]
## Steps to reproduce
Get your neon account into a state where you are "locked" waiting for operations to complete
![image](https://github.com/neondatabase/create-branch-action/assets/126919187/0c3d6771-1316-487f-9248-ab711f8123fc)

## Expected result

The github action to fail -- or ideally, retry

## Actual result

Variable outputs are null

## Logs, links
<img width="1472" alt="image" src="https://github.com/neondatabase/create-branch-action/assets/126919187/dc0610f2-cc17-4752-b9a9-0047f261282c">

**Comment by duskpoet** [comment]
Hey! Retry logic now has been added to the action, should resolve the issue

**Comment by jbwc** [comment]
Great thanks! Updating now
