### ISSUE TITLE
Bug with branch names 'Contains' Substring

### ISSUE THREAD

**Issue by achadee** [neondatabase/create-branch-action#29]
There is an issue which I think is on this line here
https://github.com/neondatabase/create-branch-action/blob/main/action.yml#L82

Will check if a branch contains a substring, the problem is that multiple branches can contain the same string, so neon picks the first one, which leads to weird behaviour 

I got around this by adding a suffix to the name, but you might want to change this to an exact match

**Comment by duskpoet** [comment]
Hey! Thanks for submitting! I think you are totally right, I will replace the "contains" check with strict equality, I think it should be this way
