### ISSUE TITLE
`neonctl` not found on Windows

### ISSUE THREAD

**Issue by canac** [neondatabase/create-branch-action#33]
## Steps to reproduce

Use this action on a `windows-latest` runner.

## Expected result

Action successfully creates a branch.

## Actual result

Action fails with a `neonctl: command not found` error.

## Environment

Runner OS: `windows-latest`
Version: `neondatabase/create-branch-action@v4`

## Logs, links
`debug.log`:

```
branch create out:\n
\nbranch create err:\n
D:\a\_temp\e64753fe-5bed-4532-a4a4-c46d1d409a40.sh: line 1: neonctl: command not found
\n
```

According to [this discussion](https://github.com/actions/setup-node/issues/477#issuecomment-1111577128), it appears that `actions/setup-node` doesn't add the yarn global bin directory to the path on Windows.

This issue is also present on https://github.com/neondatabase/delete-branch-action

**Comment by duskpoet** [comment]
Thanks for noticing! Can you validate the latest release, please?

**Comment by canac** [comment]
@duskpoet Yes, it seems to work now. Thanks for the fix!
