### ISSUE TITLE
Main branch url being returned if branch already exists because `branch_id` lookup returns empty

### ISSUE THREAD

**Issue by justapithecus** [neondatabase/create-branch-action#34]
## Steps to reproduce

* Attempt to create a branch using a `branch_name` that already exists

## Expected result

* Correct `branch_id`, `db_url_with_pooler` and `db_url` are returned

## Actual result

* `branch_id` is empty
* `main` branch `db_url_with_pooler` and `db_url` are emitted as output variables

## Environment

* `ubuntu-latest` executor
* uses: `neondatabase/create-branch-action@v4`

## Logs, links
```
branch create out:\n
\nbranch create err:\n
ERROR: branch with the provided name "****" already exists
\n
branch exists, branch id: \n

```

Possibly an issue here:
```
          # Get the branch id by its name. We list all branches and filter by name
          branch_id=$(neonctl branches list --project-id ${{ inputs.project_id }} -o json \
              | jq -r '.[] | select(.name == "${{ inputs.branch_name }}") | .id')

```

**Comment by duskpoet** [comment]
can you share more details, please, I can't reproduce it with an arbitrary branch name

**Comment by duskpoet** [comment]
Can't reproduce
