### ISSUE TITLE
Creation of a branch with a name starting with # results in "ERROR: name cannot be empty"

### ISSUE THREAD

**Issue by gaborcs** [neondatabase/create-branch-action#40]
## Steps to reproduce
Run neondatabase/create-branch-action@v4
  with:
    project_id: ***
    branch_name: #441-release-integration
    api_key: ***
    username: ***
    database: neondb
    prisma: false
    suspend_timeout: 0

## Expected result
The branch should be created.

## Actual result
ERROR: name cannot be empty

**Comment by tomassabol** [comment]
same issue here

**Comment by duskpoet** [comment]
It should be fixed now! Sorry for taking so long on this 😓
