### ISSUE TITLE
db_url doesn't contain sslmode=require

### ISSUE THREAD

**Issue by noqcks** [neondatabase/create-branch-action#44]
## Steps to reproduce

Use the create-branch-action

## Expected result

db_url output to contain the full connection string including `sslmode=require`

## Actual result

db_url doesn't contain `sslmode=require`

**Comment by duskpoet** [comment]
It's a no brainer to add that, but that would likely break users who add it manually... 
I guess I will release a new major version

**Comment by hussamkhatib** [comment]
That will not allow anyone to use other sslmodes.
https://neon.tech/docs/connect/connect-securely

**Comment by duskpoet** [comment]
I guess the default of `sslmode=require` with a possibility to change works for everyone?

**Comment by duskpoet** [comment]
Ok, in the new v5 version sslmode=require is appended by default, with an option to override
