### ISSUE TITLE
Question: How can I pass outputs of the create-branch-action into next job of a gh action

### ISSUE THREAD

**Issue by hussamkhatib** [neondatabase/create-branch-action#46]
![image](https://github.com/neondatabase/create-branch-action/assets/52914487/bd5ca264-2053-4832-a2b1-5ca2bbb14797)

### Context: I am using turborepo with 3 apps to build.
I am trying to separate creating a branch in Neon as a single and building the apps as another job. So that we don't have to run the create-branch-action multiple times.

### What I tried:
I copied over the [source action](https://github.com/neondatabase/create-branch-action/blob/main/action.yml) into my local environment and tried removing the line where [masking](https://github.com/neondatabase/create-branch-action/blob/main/action.yml#L75) is added 

Note: I can still run the create-branch-action for all the apps where I wouldn't have multiple jobs in the gh action, but It would be great to just run it once, and pass it into the next job where each app utilizes the URL directly instead of using the create-branch-action

**Comment by duskpoet** [comment]
Hello, Hussam!
I would suggest reusing the action - if the branch already exists the action will return credentials for it.
Otherwise you would need some secret storage to pass the connections string https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#workflow

**Comment by hussamkhatib** [comment]
Ah, that's more friction, I would want to go ahead with reusing the action as you suggest.
