### ISSUE TITLE
Using `yarn add` tries installing entire `package.json` and fails

### ISSUE THREAD

**Issue by blakeembrey** [neondatabase/create-branch-action#9]
## Steps to reproduce

1. Create a new repo, use NPM, and have something that NPM doesn't fail on but warns (e.g. incompatible node.js version).
2. Try using `create-branch-action` after https://github.com/neondatabase/create-branch-action/pull/8 was merged.

## Expected result

This action works.

## Actual result

```
error ...: The engine "node" is incompatible with this module. Expected version ">=19". Got "18.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Process completed with exit code 1.
```

## Logs, links
-

**Comment by duskpoet** [comment]
Should be solved in v.4.1.1
